### ISSUE TITLE
A bug about "/dmp_bbo/demoImitationAndOptimization.cpp"

### ISSUE THREAD

**Issue by xiaogengyaokeyan** [stulp/dmpbbo#15]
#when I run the "/dmp_bbo/demoImitationAndOptimization.cpp", there is an error. After printing out the "breakpoint", I find the return of the function "Trajectory::getRangePerDim()" wrong. Indeed, the return should be transposed so that it is a vector. I change the code like this:
![111](https://cloud.githubusercontent.com/assets/21303945/26750066/399108a0-484c-11e7-909d-4898162ed544.png)
 And it works well.

**Comment by stulp** [comment]
I do not understand the error or the solution. 

In the current release, I do not get an error when running the demoImitationAndOptimization executable (neither in debug nor normally compiled version).

ys is a Matrix, so taking the minCoeff returns a Vector not a Matrix. And a Vector is what the return value of the function should be. So it should all be good. Why turn it in to a Matrix first, then needs to be transposed?

Perhaps you are using an older version of Eigen? (I currently have 3.2.92)
