### ISSUE TITLE
Compile issues on Ubuntu 16.04

### ISSUE THREAD

**Issue by kazuotani14** [stulp/dmpbbo#16]
I am getting some compile issues on Ubuntu 16.04 concerning boost::serialization. Not sure what's going on here, but any help would be appreciated! 

Screenshot shows error when compiling with debug symbols, but this was recreated on two computers in normal compile mode as well. 
![screenshot from 2017-06-15 10-11-15](https://user-images.githubusercontent.com/13681069/27171962-b36d44b6-51b3-11e7-80c5-f27f258c079e.png)

**Comment by stulp** [comment]
The code compiles on my 16.04 Ubuntu, with libboost-dev version 1.58.0.1ubuntu1.
No complaints from Travis either: https://travis-ci.org/stulp/dmpbbo

What boost version do you have?

**Comment by kazuotani14** [comment]
I have version 1.58.0.1ubuntu1 as well.
