### ISSUE TITLE
Comparison to None in python

### ISSUE THREAD

**Issue by bogdan-paulis** [stulp/dmpbbo#17]
At the moment there are a few comparisons to None and when running I just get:

FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if samples==None:

But in the latest numpy version it is treated as an error. 
ValueError: the truth value of an array with more than one element is ambiguous.
Use a.any() or a.all()

**Comment by stulp** [comment]
Thanks for pointing this out. I fixed this issue in 5430f5ec5d1. In the 4 preceding commits, I fixed some other FutureWarnings also.
