### ISSUE TITLE
License LGPL or GPL?

### ISSUE THREAD

**Issue by eturner303** [stulp/dmpbbo#18]
Hi, I noticed your library has 2 different license files (LGPL and GPL) checked in -- under what license is this library licensed?

Thank you!

**Comment by stulp** [comment]
100% LGPL. 

The GPL is the basic licence, and the L-GPL licence extends it. Adding the two files is how understood it should be done, though I think this is indeed a bit strange. 

Spoiler alert: I've been able to make several parts of the C++ code real-time, and will make a new release this code soon (i.e. within the next two days).

**Comment by stulp** [comment]
In commit 76084c0f27c6c5f6f3, I've included the standard GitHub LGPL 2.1 license now.
