### ISSUE TITLE
Seg fault in deserialized dmp->analyticalSolution

### ISSUE THREAD

**Issue by gokhansolak** [stulp/dmpbbo#20]
I serialize and deserialize a Dmp similar to testDmpSerialization.cpp. Then, calling _dmp->analyticalSolution()_ leads to a sigsegv error. 

Crash occurs at 560th line of Dmp.cpp: 
`perturbation(i_dim) = (*analytical_solution_perturber_)();`

Apparently, after deserialization  _analytical_solution_perturber__ is not NULL anymore. But I didn't set it before serialization. Also, there is no perturbation property in a serialized dmp.xml file.

As a workaround, calling _dmp->set_perturbation_analytical_solution()_ after deserialization solves the problem:
```
{
    // create and open an archive for input
    ifstream ifs;
    ifs.open(dmp_filename.c_str());
    boost::archive::xml_iarchive ia(ifs);
    // read class state from archive
    ia >> BOOST_SERIALIZATION_NVP(dmp_);
  } // brackets for auto-closing streams

  // to avoid seg fault in analyticalSolution
  dmp_->set_perturbation_analytical_solution(0.0);
```

Built with static libraries, debug mode. Ubuntu 16.04.

**Comment by stulp** [comment]
Thanks for pointing this out. It was indeed a clear bug, which I was able to reproduce in commit 22791648e2.

In commit 39b1cf21, I fixed it. At least the Seg fault I was able to reproduce disappeared on my side. If you still have the Seg fault, please reopen the issue.

Note that there is no longer need for the workaround. There is a new member variable "perturbation_standard_deviation_" in the Dmp class which is serialized.
