### ISSUE TITLE
Make install doesn't install eigen_realtime header

### ISSUE THREAD

**Issue by gokhansolak** [stulp/dmpbbo#25]
Make install doesn't install eigen_realtime header. Building a code that includes Dmpbbo fails with _fatal error: eigen_realtime/eigen_realtime_check.hpp no such file or directory_ .

Copying the header into _/usr/local/include_ manually solves the problem:
```
mkdir /usr/local/include/eigen_realtime
cp path-to-dmpbbo/src/eigen_realtime/eigen_realtime_check.hpp /usr/local/include/eigen_realtime/
```

System: Ubuntu 16.04

**Comment by graiola** [comment]
Hi, there is no need to copy and paste the file by hand.
The fix has to be done in the CMakeLists.txt inside the src folder.
I will do a pr for that.
