### ISSUE TITLE
Installation Requirements

### ISSUE THREAD

**Issue by jenskober** [stulp/dmpbbo#29]
I installed/compiled dmpbbo on a VirtualBox of fresh Ubuntu 16.04 (desktop) install.

Eigen3 is still required but went missing after a recent commit (Ubuntu now contains a high enough version, so custom install is not required) but should be added to apt-get list, i.e., libeigen3-dev

For the Python part tkinter (python3-tk) was not included by default when installing python3 via apt-get but also required.

In general it would be nice to mention which versions of Debian/Ubuntu this has been tested with.

openjournals/joss-reviews#1225

**Comment by graiola** [comment]
I created a PR #30

**Comment by jenskober** [comment]
I would also add that to INSTALL.txt

unrelated note: some of the Python files also require latex for the plotting, e.g., demoDmpWrapper.py
I had to install texlive and texlive-latex-extra

**Comment by stulp** [comment]
We've rewritten INSTALL.md. If it is satisfactory now, could you close this issue?

**Comment by jenskober** [comment]
thanks, looks good now!
