### ISSUE TITLE
Demo instructions

### ISSUE THREAD

**Issue by stulp** [stulp/dmpbbo#32]
It would be nice to add some instructions on how to call the demos. This is mentioned for demoDynamicalSystems in the tutorial, however the corresponding plotDynamicalSystem.py does not seem to exist.
 
(splitting #31 into several separate issues)

**Comment by stulp** [comment]
Yes, this is not done consistently throughout the documentation. Here is what I propose:

1) The doxygen documentation no longer documents the demos (only the API, and it includes the tutorials)

2) Instead the demos are documented in a README.md file in 

This way, the documentation for the demos is close to the demos source code themselves, and doxygen does not need to be called to quickly have access to these explanations.

**Comment by jenskober** [comment]
@stulp Thanks for splitting issue #31 up!
I'm in favor of that suggestion.

**Comment by stulp** [comment]
Thanks for the feedback; I assigned myself to do it.
