### ISSUE TITLE
Unclear how to call Python wrappers

### ISSUE THREAD

**Issue by stulp** [stulp/dmpbbo#33]
The Python Wrappers are nice, but it is also not 100% clear how to call them. You need to "make install" and then call them from the original source directory, which I didn't find very intuitive.

(splitting #31 into several separate issues)

**Comment by stulp** [comment]
You are right @jenskober, it is not very intuitive... It is a compromise. Basically, results are saved to txt files (sometimes xml) in both Python and C++ versions. To check that they are compatible, the Python script calls the binary, and then reads the txt files it generated. In principle this could be done with Python bindings or something, but then the correct format of the txt files would no longer be tested. Hence this rather awkward approach of calling binaries from Python.

Given that, I do not see any other way of doing it. I.e. the binary must be installed before the Python wrapper can call it. And I do not want to start the compilation from a Python script. So I rather give a an error message saying that you should make install if you haven't done so yet.

I have now though of a way to make things better (it will still be a compromise though):

1) standalone C++ demos (that don't really need the Python wrapper) are installed in bin_demos

2) C++ demos who rely on calling the Python wrapper are not installed in bin_demos, so the user is not tempted to execute them standalone.

Still, I feel there must be a much easier way of meeting the requirements I sketched above.

(assigning to @graiola to get his perspective)

**Comment by jenskober** [comment]
Thanks for the detailed explanation. Tricky indeed...

What you could consider additionally, is to copy the Python wrappers to where the binaries reside via cmake.

**Comment by stulp** [comment]
I considered the option you mentioned, and implemented it by creating soft links (see the install_python branch). However, it's a mess because of imports in the Python scripts, which must be robust to the many locations where they could be (source dir, build dir, bin dir, etc.). And the CMakeLists.txt become really ugly and obfuscated. I could make it work, but it would be ugly and very error-prone. So I am not pursuing this.

Now I am trying something different, which seems like a bad idea at first, but I think it is the best solution. The idea is to install e.g. the executable demoExponentialSystem in demos/dynamicalsystems. There and only there. Advantages:

- it is right next to the Python wrapper demoExponentialSystemWrapper.py, and also right next to the documentation (once I've written it ;-)
- no need to be robust against different locations of the Python script (because it is not copied or symlinked)
- only minimal changes to the code (see commit 8f1b32c)

This must seem like an obviously bad idea because I am installing executables in the source directory. 

But is it that bad? Basically, dmpbbo (C++ part) is a library for developers (in src/), with some demos to help you get started (in demos/). For programming convenience, it is a good idea to install the libraries in e.g. /usr/local/lib (same for include files). But do you really want to call the demoExponentialSystem from anywhere, as you would with "ls" or "mv"? Probably not. And sometimes it is even a bad idea, because the idea was to call the Python wrapper, not the binary itself. This last link is made most obvious by installing in demos/

If I hear no outcry from @jenskober or @graiola, I will pursue with this.

(Of course, the executable should still be robust towards calling it without (the right) parameters, and use sensible default or give sensible error messages.)
