### ISSUE TITLE
Consistency between help for demoDynamicalSystems and demoDmp*

### ISSUE THREAD

**Issue by stulp** [stulp/dmpbbo#34]
The help for demoDynamicalSystems is quite nice, for the dmp demos I'd suggest changing it to the same format (with a complete example of a call)

(splitting #31 into several separate issues)

**Comment by stulp** [comment]
@jenskober Can I close this one, now that the documentation makes explicit that it is much better to call the Python wrapper files rather than the executables themselves?

**Comment by jenskober** [comment]
Thanks, looks good now!
