### ISSUE TITLE
Suggest adding in start / end markers to demoOptimizationDmp.py

### ISSUE THREAD

**Issue by studywolf** [stulp/dmpbbo#42]
something like 
```
    # Plot start / end markers on trajectory
    ax_rollout.plot(h[0].get_xdata()[0], h[0].get_ydata()[0], 'rx', mew=3, label='start')
    ax_rollout.plot(h[0].get_xdata()[-1], h[0].get_ydata()[-1], 'bx', mew=3, label='end')
    plt.legend()
```
after line 107 in `runOptimizationTask.py` just adds a start and end marker to the demo. Just a suggestion to make it a little easier to parse on first glance:

![Optimization_with_covar_update=decay](https://user-images.githubusercontent.com/2473097/55043889-8dc87680-500e-11e9-9d24-a1e1f07b28a7.png)

**Comment by stulp** [comment]
I've added that in #f18090a.

Please note that adding these labels is done in the plotRollout function in TaskViapoint. The (black-box) optimization algorithm does not know what it is optimizing (hence "black-box"), so runOptimizationTask does not (and should not) have any knowledge of how to plot the rollouts. Therefore, it calls plotRollout in the Task of TaskSolver, see:
https://github.com/stulp/dmpbbo/blob/master/python/dmp_bbo/runOptimizationTask.py#L93

Object-oriented design thus allows me to keep the knowledge about **what** is being optimized (in TaskViapoint and other Tasks) separate from **how** to optimize it (in runOptimization functions).
