### ISSUE TITLE
Installing serialization headers

### ISSUE THREAD

**Issue by gokhansolak** [stulp/dmpbbo#55]
When I install DMPBBO in a new PC using the release build: 
```
mkdir -p build_dir; cd build_dir; cmake .. -DCMAKE_BUILD_TYPE=Release; make; make Docs
sudo make install
```
It does not copy the `serialization.hpp` headers into `/usr/local/include/..` directories. So it gives `fatal error: dmp/serialization.hpp: No such file or directory` at compilation.

It works fine when doing the debug build:
```
mkdir -p build_dir; cd build_dir; cmake .. -DCMAKE_BUILD_TYPE=Release; make; make Docs
sudo make install
```

**Comment by stulp** [comment]
It works for me (Ubuntu 18.04), and I cannot reproduce the error.

When looking at the [CMakeLists.txt file](https://github.com/stulp/dmpbbo/blob/d2fe4cb1e10fc7d4f8890f329690200de7a52234/src/dynamicalsystems/CMakeLists.txt#L5), it also appears that all hpp files (including serialization.hpp) are installed:

    file(GLOB HEADERS *.hpp)
    install(FILES ${HEADERS} DESTINATION ${INCLUDE_INSTALL_DIR}/dynamicalsystems/)

I cheched this for the CMakeLists.txt files for all three serialization.hpp files in `dynamicalsystems/`, `functionapproximators/`, and `dmp/`. In your case, are all three serialization.hpp files not installed, or only one of them? (the answer to that question could help me debug).

Of course, you need sudo rights to do the install. But this you apparently have, or it would not install anythingn in /usr/

**Comment by gokhansolak** [comment]
I just had a chance to do a clean install, it installed the headers properly. Maybe something else was wrong with my setup then.
