### ISSUE TITLE
some broken links in tutorial pages

### ISSUE THREAD

**Issue by HiroIshida** [stulp/dmpbbo#56]
1) In the [tutorial page for DMP](https://github.com/stulp/dmpbbo/blob/master/tutorial/dmp.md#dynamical-movement-primitives), maybe all citation link seems to be broken. 
2) In the [tutorial page for BBODMP](https://github.com/stulp/dmpbbo/blob/master/tutorial/dmp_bbo.md#optimizing-dmp-dofs-in-parallel) links for  `runOptimizationTask()` seems to be broken.

**Comment by stulp** [comment]
Thanks for pointing this out. These are remnants from moving the tutorial from Doxygen to Markdown. The links you mention are now fixed (there may be more...)
