### ISSUE TITLE
Broken link in the readme

### ISSUE THREAD

**Issue by AlexanderFabisch** [stulp/dmpbbo#86]
Hi,

I just wanted to point out that the first link in the readme points to nothing:

> This repository provides an implementation of dynamical systems, function approximators, [dynamical movement primitives](http://www-clmc.usc.edu/Resources/Details?id=2663), and black-box optimization with evolution strategies, in particular the optimization of the parameters of dynamical movement primitives.

**Comment by stulp** [comment]
Thanks a lot for pointing this out!
